/**
 * Type declarations for datafusion-wasm.
 * Generated by wasm-bindgen, stub provided for development before WASM build.
 */

export class WasmQueryEngine {
  constructor()
  register_table(name: string, ipc_bytes: Uint8Array): number
  execute_sql(sql: string): Promise<Uint8Array>
  reset(): void
  free(): void
}

/**
 * Initialize the WASM module. Must be called before using any exports.
 */
export default function init(): Promise<void>
