[package]
name = "micromegas-telemetry"
description = "structures and functions common to both analytics and ingestion stacks for micromegas"
keywords.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
micromegas-transit.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
ciborium.workspace = true
http.workspace = true
hyper.workspace = true
lz4.workspace = true
object_store.workspace = true
serde.workspace = true
url.workspace = true