[package]
name = "micromegas-transit"
description = "low overhead serialization, part of micromegas"
keywords.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
micromegas-derive-transit = { path = "derive", version = "^0.4" }

anyhow.workspace = true
lazy_static.workspace = true
serde.workspace = true
uuid.workspace = true

# can't use micromegas-tracing, would cause a circular dependency
log.workspace = true

[dev-dependencies]
memoffset.workspace = true
