[package]
name = "write-perfetto"
description = "Utility to write Perfetto traces from analytics service"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "write-perfetto"
path = "src/main.rs"

[[bin]]
name = "validate-perfetto"
path = "src/validate_trace.rs"

[dependencies]
micromegas.workspace = true
micromegas-analytics.workspace = true
micromegas-perfetto.workspace = true

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap = { version = "4.0", features = ["derive"] }
datafusion.workspace = true
futures.workspace = true
tokio.workspace = true
tonic.workspace = true
prost.workspace = true