[package]
name = "telemetry-admin"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-blob-storage.workspace = true

micromegas-analytics.workspace = true
micromegas-telemetry-sink.workspace = true
micromegas-tracing.workspace = true
micromegas-transit.workspace = true

anyhow.workspace = true
clap.workspace = true
json.workspace = true
lz4.workspace = true
prost.workspace = true
sqlx.workspace = true
tokio.workspace = true

[dev-dependencies]
lgn-test-utils = { path = "../lgn-test-utils" }
fs_extra = "1.2"
