name: Grafana Plugin

on:
  push:
    branches:
      - main
    paths:
      - 'grafana/**'
      - 'typescript/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/grafana-plugin.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'grafana/**'
      - 'typescript/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/grafana-plugin.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Run Grafana CI validation
        run: python3 build/grafana_ci.py

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        working-directory: grafana

      - name: Start grafana docker
        run: yarn server -d
        working-directory: grafana

      - name: Run e2e tests
        run: yarn e2e
        working-directory: grafana

      - name: Stop grafana docker
        run: docker compose down
        working-directory: grafana
